version: '3'
services:
  lede:
    build:
      dockerfile: docker/openwrt/Dockerfile
      context: .
    volumes:
      - ./Projects/:/root/Projects
    working_dir: /root/Projects
    entrypoint:
        - /bin/bash
  arm7:
    build:
      dockerfile: docker/arm7/Dockerfile
      context: .
    volumes:
      - ./Projects/:/root/Projects
    working_dir: /root/Projects
    entrypoint:
        - /bin/bash
