version: '3'
services:
  mipsel-openwrt-linux-musl:
    build:
      dockerfile: docker/linux/Dockerfile
      context: .
    volumes:
      - ./Projects/:/root/Projects
    working_dir: /root/Projects
    entrypoint:
        - /bin/bash
        # - docker/entrypoint.sh
