version: '3'
services:
  lede:
    build:
      dockerfile: docker/openwrt/Dockerfile
      context: .
    volumes:
      - ./Projects/:/root/Projects
    working_dir: /tmp
    entrypoint:
        - /bin/bash
